### ISSUE TITLE
missing dependency?

### ISSUE THREAD

**Issue by bwlang** [EnginesOn/galaxy_tools#1]
I  get this when i attempted to run multiqc for the first time.
Installation appears to have gone ok... 
missing dependency?

I tried installing pyparsing in the galaxy venv, but that did not seem to work.

<pre>
Traceback (most recent call last):
  File "/mnt/galaxy/data/galaxy/tool-deps/multiqc/0.6/engineson/package_multiqc_0_6/68eebe70b537/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==0.6', 'multiqc')
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyparsing!=2.0.4,!=2.1.2,>=1.5.6' distribution was not found and is required by matplotlib
</pre>

**Comment by cmonjeau** [comment]
Hi bwlang,

could you take a look on the INSTALLATION.log file for the package_multiqc_0_6. Installation must install matplot and all dependencies. On my side, I have these lines on my INSTALLATION.log:

> Using /root/galaxy/.venv/lib/python2.7/site-packages
> Searching for pyparsing==2.1.1
> Best match: pyparsing 2.1.1
> Adding pyparsing 2.1.1 to easy-install.pth file

Could you tell me if you see some errors on this file?
Could you check the good installation of libpng and freetype packages too?

Thanks,
Cyril

**Comment by bwlang** [comment]
I can't see anything wrong in the log
I have:
Searching for pyparsing==2.1.0
Adding pyparsing 2.1.0 to easy-install.pth file
Using /home/galaxy/galaxy/.venv/lib/python2.7/site-packages

I think i understand the problem, it seems that the virtual environment on my cluster is different from the env on the galaxy web node.
When i manually installed pyparsing to the cluster venv, the tool is able to run (sort of).
I guess the tool installation is done on the web node and uses environmental dependencies instead of building everything from scratch.

I'm not sure if you consider this a bug or not...
